# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebe226d457d3e0bfbe7666f490445974b1f9356d370c20db6bf675aad1d05d77fc797d55f058757273148762514b9a5de7a203e1d21af9d770fe88683fb3a4bd

test:
  secret_key_base: 35e895faf68ec858ae0cc6fd6568d7a34f7a5c4f88d438bc41bc09c8dc10c8a380d85063eeabeab79757be1a956dd639861195bffeae4ea194769db7739556a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
